spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: ontology-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/ontology/**
        - id: projects-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/projects/**
        - id: classes-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/classes/**
        - id: class-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/class/**
        - id: property-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/property/**
        - id: individual-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/individual/**
        - id: instance-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/instance/**
        - id: reasoning-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/reasoning/**
        - id: collaboration-service
          uri: lb://collaboration-service
          predicates:
            - Path=/api/collaboration/**
        - id: version-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/version/**
        - id: search-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/search/**
        - id: annotation-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/annotation/**
        - id: metadata-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/metadata/**
        - id: relationship-service
          uri: lb://ontology-service
          predicates:
            - Path=/api/relationship/**

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,gateway

  endpoint:
    refresh:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8762/eureka/
  instance:
    preferIpAddress: true