spring:
  application:
    name: user-service
  main:
    sources: com.by.open.ontology.userservice.UserServiceApplication
  data:
    mongodb:
      uri: mongodb://localhost:27017/webprotege
      database: webprotege

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8762/eureka/
  instance:
    preferIpAddress: true