spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/webprotege
      database: webprotege

server:
  port: 8081
  debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8762/eureka/
  instance:
    preferIpAddress: true