server:
  port: 8085

spring:
  application:
    name: admin-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/openontology

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.by.open.ontology: DEBUG